# Generated by Django 4.0.3 on 2022-06-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('qunatity', models.IntegerField(max_length=200)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
