# Generated by Django 4.0.3 on 2022-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement_App', '0002_bookdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='qunatity',
            field=models.IntegerField(),
        ),
    ]
